name: Test

on:
  pull_request:

jobs:
  test:
    name: Run type checker and tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: npm typecheck
      - run: npm test
